
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: <your_sql_password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: <from_email_id>
    password: <app_password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
JWT_SECRET: <your secret key>