
server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: your_sql_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin12

  mail:
    host: smtp.gmail.com
    port: 587
    username: from_email_id
    password: app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
